<a href="https://colab.research.google.com/github/muhammadhilal494/deep-learning-lab/blob/master/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.version.VERSION

'2.20.0'

In [ ]:
print(tf.__version__)

2.20.0


In [ ]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(4)

c = a + b

print(c)

tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
x1=tf.constant([1,2,4,5])
x2=tf.constant([2,3,4,5])

#result = tf.multiply(x1,x2)
result=x1*x2

print(result)

tf.Tensor([ 2  6 16 25], shape=(4,), dtype=int32)


In [ ]:
import tensorflow as tf

a = tf.constant(0.3, dtype=tf.float32)  # or any initial value
b = tf.constant(0.5, dtype=tf.float32)

c = a + b
print(c)

tf.Tensor(0.8, shape=(), dtype=float32)


In [ ]:
import tensorflow as tf

def compute(a, b):
    return a + b

c = compute(1, 4)
print(c)

5


In [ ]:
import tensorflow as tf

a = tf.constant([1, 2, 3], dtype=tf.float32)
b = tf.constant([4, 2, 1], dtype=tf.float32)

c = a + b
print(c)

tf.Tensor([5. 4. 4.], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf

x = tf.Variable([1.0])
w = tf.Variable([3.0])

c = x * w

print(c)

tf.Tensor([3.], shape=(1,), dtype=float32)
