<a href="https://colab.research.google.com/github/muhammadhilal494/deep-learning-lab/blob/master/04_sonar_single_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [6]:
from google.colab import files

print("Click on 'Choose Files' to select sonar.csv from your computer")
uploaded = files.upload()

Click on 'Choose Files' to select sonar.csv from your computer


Saving sonar.csv to sonar (1).csv


In [7]:
df = pd.read_csv("sonar.csv", header=None)
print(len(df.columns))

61


In [9]:
# View first few rows
print(df.head())

       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   

In [10]:
# View shape
print(df.shape)

(208, 61)


In [11]:
print(df.dtypes)


0     float64
1     float64
2     float64
3     float64
4     float64
       ...   
56    float64
57    float64
58    float64
59    float64
60     object
Length: 61, dtype: object


In [12]:
# Check for missing values
print(df.isnull().sum())

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64


In [13]:
X = df[df.columns[0:60]].values
print("Features shape:", X.shape)
print(X)

Features shape: (208, 60)
[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


In [14]:
y = df[df.columns[60]]
print("\nLabels shape:", y.shape)
print("Unique labels:", y.unique())
print(y)


Labels shape: (208,)
Unique labels: ['R' 'M']
0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object


In [15]:
from sklearn.preprocessing import LabelEncoder

y_labelencoder = LabelEncoder()
y = y_labelencoder.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [20]:
y = y.reshape(-1, 1)
print("Reshaped y:", y.shape)

onehotencoder = OneHotEncoder(sparse_output=False)
Y = onehotencoder.fit_transform(y)

print("One-Hot Encoded Y:")
print(Y)

Reshaped y: (208, 1)
One-Hot Encoded Y:
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0

In [34]:
train_x, test_x, train_y, test_y = train_test_split(
    X, Y, test_size=0.20, random_state=42
)

train_x = tf.cast(train_x, tf.float32)
test_x = tf.cast(test_x, tf.float32)
train_y = tf.cast(train_y, tf.float32)
test_y = tf.cast(test_y, tf.float32)

# Print shapes
print("Training X shape:", train_x.shape)
print("Training Y shape:", train_y.shape)
print("Testing X shape:", test_x.shape)
print("Testing Y shape:", test_y.shape)

Training X shape: (166, 60)
Training Y shape: (166, 2)
Testing X shape: (42, 60)
Testing Y shape: (42, 2)


In [35]:
# Hyperparameters
learning_rate = 0.01
training_epochs = 100
n_class = 2

In [36]:
# Initialize histories
cost_history = []
mse_history = []

In [37]:
# Model variables
W = tf.Variable(tf.zeros([60, n_class], dtype=tf.float32))
b = tf.Variable(tf.zeros([n_class], dtype=tf.float32))

In [38]:
# Model function
def perceptron_model(x):
    logits = tf.matmul(x, W) + b
    pred = tf.nn.softmax(logits)
    return pred, logits

In [39]:
# Loss function
def loss_fn(y_true, logits):
    return tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(y_true, logits)
    )

In [40]:
# Optimizer
optimizer = tf.optimizers.SGD(learning_rate=learning_rate)

In [41]:
# ===== Training Loop =====
print("Training the Sonar Perceptron Model...")
print("=" * 60)

for epoch in range(training_epochs):
    # Train on training data
    with tf.GradientTape() as tape:
        _, logits_train = perceptron_model(train_x)
        cost = loss_fn(train_y, logits_train)

    # Compute gradients and update weights
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))

    # Store cost
    cost_history.append(cost.numpy())

    # Evaluate on test data
    pred_y, _ = perceptron_model(test_x)

    # Calculate MSE
    mse = tf.reduce_mean(tf.square(pred_y - test_y))
    mse_history.append(mse.numpy())

    # Print progress
    print(f"epoch: {epoch:3d} - cost: {cost.numpy():.6f} - MSE: {mse.numpy():.6f}")

print("=" * 60)
print("Training Complete! ✅")

Training the Sonar Perceptron Model...
epoch:   0 - cost: 0.693147 - MSE: 0.249607
epoch:   1 - cost: 0.692871 - MSE: 0.249227
epoch:   2 - cost: 0.692604 - MSE: 0.248862
epoch:   3 - cost: 0.692343 - MSE: 0.248508
epoch:   4 - cost: 0.692090 - MSE: 0.248167
epoch:   5 - cost: 0.691844 - MSE: 0.247837
epoch:   6 - cost: 0.691603 - MSE: 0.247518
epoch:   7 - cost: 0.691367 - MSE: 0.247209
epoch:   8 - cost: 0.691137 - MSE: 0.246909
epoch:   9 - cost: 0.690911 - MSE: 0.246619
epoch:  10 - cost: 0.690689 - MSE: 0.246337
epoch:  11 - cost: 0.690471 - MSE: 0.246063
epoch:  12 - cost: 0.690256 - MSE: 0.245797
epoch:  13 - cost: 0.690045 - MSE: 0.245539
epoch:  14 - cost: 0.689836 - MSE: 0.245287
epoch:  15 - cost: 0.689631 - MSE: 0.245042
epoch:  16 - cost: 0.689427 - MSE: 0.244803
epoch:  17 - cost: 0.689226 - MSE: 0.244570
epoch:  18 - cost: 0.689028 - MSE: 0.244343
epoch:  19 - cost: 0.688831 - MSE: 0.244121
epoch:  20 - cost: 0.688636 - MSE: 0.243904
epoch:  21 - cost: 0.688443 - MSE: 0.

In [42]:
def calculate_accuracy(pred, y_true):
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y_true, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    return accuracy.numpy()

In [43]:
# Get predictions on test data
pred_test, _ = perceptron_model(test_x)

# Calculate accuracy
accuracy = calculate_accuracy(pred_test, test_y)
print("Accuracy:", accuracy)

Accuracy: 0.78571427
